### ISSUE TITLE
ValueError: Not enough values to unpack

### ISSUE THREAD

**Issue by Musikman** [Musikman/Pendulum#1]
Attempting to run pendulum3rd.py generates the following output:

Traceback (most recent call last):
  File "C:\Users\--\pendulum3rd.py", line 50, in <module>
    y = odeint(deriv, y0, t, args=(L1, L2, L3, m1, m2, m3))
  File "C:\Users\--\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\scipy\integrate\odepack.py", line 241, in odeint
    output = _odepack.odeint(func, y0, t, args, Dfun, col_deriv, ml, mu,
  File "C:\Users\--\pendulum3rd.py", line 16, in deriv
    theta1, z1, theta2, z2, theta3, z3 = y
ValueError: not enough values to unpack (expected 6, got 4)

**Comment by Musikman** [comment]
Edit was to swap "~~" to "--" since markdown is active

**Comment by Musikman** [comment]
The issue was stemming from the lack of initial condition being provided for the third pendulum hence why the ODEINT function was expecting 6 values and got 4. Adjusted y0 to reflect a third initial condition.
